### ISSUE TITLE
RUST | How to write & compile RUST in vscode.dev?

### ISSUE THREAD

**Issue by beingminimal** [microsoft/vscode-wasm#102]
Hi There!

For new developers and early adopters we need a step by step guide for the RUST part.
This [blog](https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi) shows the python part only so we are not able to figure out how to use this for rust.

So please update docs either in vs code or provide a new blog for RUST implementation step by step guide.
Thank You

**Comment by beingminimal** [comment]
@dbaeumer Please help to solve this. Awaiting your response. Thanks

**Comment by dbaeumer** [comment]
You first need to RUST compiler that is compiled to WASM/WASI. This is currently not available. For a detailed discussion see https://github.com/rust-lang/miri/issues/722. 

I will close the issue since there is nothing I can provide until a RUST compiler in WASM exists. @beingminimal you might want to contribute to Rust first to make this happen.
