### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by emil14** [microsoft/vscode-wasm#124]
release version of 'ms-vscode.wasm-wasi-core' extension because it has no release version.

**Comment by floooh** [comment]
+1, my WIP extension at https://marketplace.visualstudio.com/items?itemName=floooh.vscode-kcide also suffers from this.

I basically need to remove the `extensionDependency` field from package.json and ask the user to install the pre-release version manually. It would be nicer if there would be a more user-friendly solution (maybe switch the extension to "preview" instead to make clear that it is still under construction?

**Comment by floooh** [comment]
Btw, one workaround to the problem is to publish your own extension which depends on the `ms-vscode.wasm-wasi-core` as pre-release. Then installing this pre-release version of your own extension will also install the pre-release version of `ms-vscode.wasm-wasi-core` without errors. When using the insiders version of VSCode, the pre-release seems to be picked automatically, in the regular VSCode version it must be explicitely selected.

**Comment by dbaeumer** [comment]
A release version of the extension is now available.
